package com.ibm.easyerp.model;

import com.ibm.easyerp.base.BasePageVo;

import java.util.Date;

public class Order extends BasePageVo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.orderNO
     *
     * @mbg.generated
     */
    private String orderNO;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.orderTime
     *
     * @mbg.generated
     */
    private Date orderTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.otherInfo
     *
     * @mbg.generated
     */
    private String otherInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.quantity
     *
     * @mbg.generated
     */
    private String quantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.customerNO
     *
     * @mbg.generated
     */
    private String customerNO;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.productNO
     *
     * @mbg.generated
     */
    private String productNO;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order
     *
     * @mbg.generated
     */
    public Order(String orderNO, Date orderTime, String otherInfo, String quantity, String customerNO, String productNO) {
        this.orderNO = orderNO;
        this.orderTime = orderTime;
        this.otherInfo = otherInfo;
        this.quantity = quantity;
        this.customerNO = customerNO;
        this.productNO = productNO;
    }

    public Order() {

    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.orderNO
     *
     * @return the value of tb_order.orderNO
     *
     * @mbg.generated
     */
    public String getOrderNO() {
        return orderNO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.orderTime
     *
     * @return the value of tb_order.orderTime
     *
     * @mbg.generated
     */
    public Date getOrderTime() {
        return orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.otherInfo
     *
     * @return the value of tb_order.otherInfo
     *
     * @mbg.generated
     */
    public String getOtherInfo() {
        return otherInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.quantity
     *
     * @return the value of tb_order.quantity
     *
     * @mbg.generated
     */
    public String getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.customerNO
     *
     * @return the value of tb_order.customerNO
     *
     * @mbg.generated
     */
    public String getCustomerNO() {
        return customerNO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.productNO
     *
     * @return the value of tb_order.productNO
     *
     * @mbg.generated
     */
    public String getProductNO() {
        return productNO;
    }
}