package com.ibm.easyerp.dao;

import com.ibm.easyerp.model.Order;
import com.ibm.easyerp.util.PageView;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

import java.util.List;

public interface OrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order
     *
     * @mbg.generated
     */
    @Delete({
        "delete from tb_order",
        "where orderNO = #{orderNO,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String orderNO);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order
     *
     * @mbg.generated
     */
    @Insert({
        "insert into tb_order (orderNO, orderTime, ",
        "otherInfo, quantity, ",
        "customerNO, productNO)",
        "values (#{orderNO,jdbcType=VARCHAR}, #{orderTime,jdbcType=TIMESTAMP}, ",
        "#{otherInfo,jdbcType=VARCHAR}, #{quantity,jdbcType=VARCHAR}, ",
        "#{customerNO,jdbcType=VARCHAR}, #{productNO,jdbcType=VARCHAR})"
    })
    int insert(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order
     *
     * @mbg.generated
     */
    int insertSelective(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "orderNO, orderTime, otherInfo, quantity, customerNO, productNO",
        "from tb_order",
        "where orderNO = #{orderNO,jdbcType=VARCHAR}"
    })
    @ResultMap("com.ibm.easyerp.dao.OrderMapper.BaseResultMap")
    Order selectByPrimaryKey(String orderNO);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order
     *
     * @mbg.generated
     */
    @Update({
        "update tb_order",
        "set orderTime = #{orderTime,jdbcType=TIMESTAMP},",
          "otherInfo = #{otherInfo,jdbcType=VARCHAR},",
          "quantity = #{quantity,jdbcType=VARCHAR},",
          "customerNO = #{customerNO,jdbcType=VARCHAR},",
          "productNO = #{productNO,jdbcType=VARCHAR}",
        "where orderNO = #{orderNO,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(Order record);

    List<Order> getAll(PageView pageView);

    List<Order> getAll2(Order order);

    int getTotal(Order order);

    List<Order> selectByOrder(Order order);

    long countByOrder(Order order);
}